#include <iostream>
#include <string>
using namespace std;

class mahasiswa // Kelas mahasiswa adalah sebuah kelas yang digunakan untuk merepresentasikan seorang mahasiswa. Kelas ini memiliki konstruktor dengan parameter yang akan dipanggil setiap kali objek mahasiswa dibuat dengan memberikan nilai untuk NIM dan Nama. Konstruktor ini akan mencetak pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai NIM dan Nama yang diberikan sebagai parameter. Dengan menggunakan konstruktor dengan parameter, kita dapat memberikan nilai awal untuk variabel anggota saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
{
private: // Variabel anggota nim dan nama dalam kelas mahasiswa digunakan untuk menyimpan informasi tentang nomor induk mahasiswa (NIM) dan nama mahasiswa. Variabel ini memiliki tipe data int untuk nim dan string untuk nama, yang memungkinkan kita untuk menyimpan nilai numerik sebagai NIM dan teks sebagai nama mahasiswa. Variabel anggota ini dapat diakses dan dimodifikasi melalui konstruktor dengan parameter yang digunakan untuk menginisialisasi nilai NIM dan Nama saat objek mahasiswa dibuat, serta melalui fungsi cetak yang digunakan untuk menampilkan informasi tersebut ke layar menggunakan cout.
    int nim;
    string nama;

public: // Konstruktor dengan parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima dua parameter, yaitu nim (nomor induk mahasiswa) dan nama (nama mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM dan Nama yang diberikan sebagai parameter akan ditampilkan. Dengan menggunakan konstruktor dengan parameter, kita dapat memberikan nilai awal untuk variabel anggota saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    mahasiswa(); // Konstruktor default adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, serta tidak menerima parameter. Konstruktor ini akan dipanggil secara otomatis setiap kali objek dari kelas tersebut dibuat tanpa memberikan nilai untuk parameter, dan biasanya digunakan untuk menginisialisasi variabel anggota dengan nilai default atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor default ini akan dipanggil saat objek mahasiswa dibuat tanpa memberikan nilai untuk NIM dan Nama, sehingga kita dapat melihat pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai NIM dan Nama yang telah diinisialisasi dengan nilai default.
    mahasiswa(int); // Konstruktor dengan satu parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima satu parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima satu parameter, yaitu nim (nomor induk mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM yang diberikan sebagai parameter akan ditampilkan, sementara Nama akan diinisialisasi dengan nilai default. Dengan menggunakan konstruktor dengan satu parameter, kita dapat memberikan nilai awal untuk variabel anggota nim saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    mahasiswa(string); // Konstruktor dengan satu parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima satu parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima satu parameter, yaitu nama (nama mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai Nama yang diberikan sebagai parameter akan ditampilkan, sementara NIM akan diinisialisasi dengan nilai default. Dengan menggunakan konstruktor dengan satu parameter, kita dapat memberikan nilai awal untuk variabel anggota nama saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    mahasiswa(int iNim, string iNama); // Konstruktor dengan dua parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima dua parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima dua parameter, yaitu nim (nomor induk mahasiswa) dan nama (nama mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM dan Nama yang diberikan sebagai parameter akan ditampilkan. Dengan menggunakan konstruktor dengan dua parameter, kita dapat memberikan nilai awal untuk variabel anggota nim dan nama saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    void cetak(); // Fungsi cetak adalah sebuah fungsi anggota dalam kelas mahasiswa yang digunakan untuk menampilkan informasi tentang mahasiswa, termasuk NIM dan Nama. Fungsi ini akan mencetak nilai NIM dan Nama mahasiswa ke layar menggunakan cout. Dengan menggunakan fungsi cetak, kita dapat dengan mudah melihat informasi lengkap tentang setiap mahasiswa yang dibuat, termasuk NIM dan Nama yang telah diinisialisasi melalui konstruktor dengan parameter atau konstruktor default.
};

