#include <iostream>
#include <string>
using namespace std;

class mahasiswa // Kelas mahasiswa adalah sebuah kelas yang digunakan untuk merepresentasikan seorang mahasiswa. Kelas ini memiliki konstruktor dengan parameter yang akan dipanggil setiap kali objek mahasiswa dibuat dengan memberikan nilai untuk NIM dan Nama. Konstruktor ini akan mencetak pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai NIM dan Nama yang diberikan sebagai parameter. Dengan menggunakan konstruktor dengan parameter, kita dapat memberikan nilai awal untuk variabel anggota saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
{
private: // Variabel anggota nim dan nama dalam kelas mahasiswa digunakan untuk menyimpan informasi tentang nomor induk mahasiswa (NIM) dan nama mahasiswa. Variabel ini memiliki tipe data int untuk nim dan string untuk nama, yang memungkinkan kita untuk menyimpan nilai numerik sebagai NIM dan teks sebagai nama mahasiswa. Variabel anggota ini dapat diakses dan dimodifikasi melalui konstruktor dengan parameter yang digunakan untuk menginisialisasi nilai NIM dan Nama saat objek mahasiswa dibuat, serta melalui fungsi cetak yang digunakan untuk menampilkan informasi tersebut ke layar menggunakan cout.
    int nim;
    string nama;

public: // Konstruktor dengan parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima dua parameter, yaitu nim (nomor induk mahasiswa) dan nama (nama mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM dan Nama yang diberikan sebagai parameter akan ditampilkan. Dengan menggunakan konstruktor dengan parameter, kita dapat memberikan nilai awal untuk variabel anggota saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    mahasiswa(); // Konstruktor default adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, serta tidak menerima parameter. Konstruktor ini akan dipanggil secara otomatis setiap kali objek dari kelas tersebut dibuat tanpa memberikan nilai untuk parameter, dan biasanya digunakan untuk menginisialisasi variabel anggota dengan nilai default atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor default ini akan dipanggil saat objek mahasiswa dibuat tanpa memberikan nilai untuk NIM dan Nama, sehingga kita dapat melihat pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai NIM dan Nama yang telah diinisialisasi dengan nilai default.
    mahasiswa(int); // Konstruktor dengan satu parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima satu parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima satu parameter, yaitu nim (nomor induk mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM yang diberikan sebagai parameter akan ditampilkan, sementara Nama akan diinisialisasi dengan nilai default. Dengan menggunakan konstruktor dengan satu parameter, kita dapat memberikan nilai awal untuk variabel anggota nim saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    mahasiswa(string); // Konstruktor dengan satu parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima satu parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima satu parameter, yaitu nama (nama mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai Nama yang diberikan sebagai parameter akan ditampilkan, sementara NIM akan diinisialisasi dengan nilai default. Dengan menggunakan konstruktor dengan satu parameter, kita dapat memberikan nilai awal untuk variabel anggota nama saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    mahasiswa(int iNim, string iNama); // Konstruktor dengan dua parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima dua parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima dua parameter, yaitu nim (nomor induk mahasiswa) dan nama (nama mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM dan Nama yang diberikan sebagai parameter akan ditampilkan. Dengan menggunakan konstruktor dengan dua parameter, kita dapat memberikan nilai awal untuk variabel anggota nim dan nama saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    void cetak(); // Fungsi cetak adalah sebuah fungsi anggota dalam kelas mahasiswa yang digunakan untuk menampilkan informasi tentang mahasiswa, termasuk NIM dan Nama. Fungsi ini akan mencetak nilai NIM dan Nama mahasiswa ke layar menggunakan cout. Dengan menggunakan fungsi cetak, kita dapat dengan mudah melihat informasi lengkap tentang setiap mahasiswa yang dibuat, termasuk NIM dan Nama yang telah diinisialisasi melalui konstruktor dengan parameter atau konstruktor default.
};

mahasiswa::mahasiswa() // Konstruktor default adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, serta tidak menerima parameter. Konstruktor ini akan dipanggil secara otomatis setiap kali objek dari kelas tersebut dibuat tanpa memberikan nilai untuk parameter, dan biasanya digunakan untuk menginisialisasi variabel anggota dengan nilai default atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor default ini akan dipanggil saat objek mahasiswa dibuat tanpa memberikan nilai untuk NIM dan Nama, sehingga kita dapat melihat pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai NIM dan Nama yang telah diinisialisasi dengan nilai default.
{

}

mahasiswa::mahasiswa(int iNim) // Konstruktor dengan satu parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima satu parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima satu parameter, yaitu nim (nomor induk mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM yang diberikan sebagai parameter akan ditampilkan, sementara Nama akan diinisialisasi dengan nilai default. Dengan menggunakan konstruktor dengan satu parameter, kita dapat memberikan nilai awal untuk variabel anggota nim saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
{
    nim = iNim; // Menetapkan nilai parameter iNim ke variabel anggota nim. Dengan menggunakan this->nim, kita dapat mengakses variabel anggota nim dalam konteks kelas mahasiswa, sehingga kita dapat memberikan nilai awal untuk variabel anggota nim saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
}

mahasiswa::mahasiswa(int iNim, string iNama) // Konstruktor dengan dua parameter adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian, tetapi menerima dua parameter untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas mahasiswa, konstruktor ini menerima dua parameter, yaitu nim (nomor induk mahasiswa) dan nama (nama mahasiswa). Saat objek mahasiswa dibuat dengan menggunakan konstruktor ini, pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM dan Nama yang diberikan sebagai parameter akan ditampilkan. Dengan menggunakan konstruktor dengan dua parameter, kita dapat memberikan nilai awal untuk variabel anggota nim dan nama saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
{
    nim = iNim; // Menetapkan nilai parameter iNim ke variabel anggota nim. Dengan menggunakan this->nim, kita dapat mengakses variabel anggota nim dalam konteks kelas mahasiswa, sehingga kita dapat memberikan nilai awal untuk variabel anggota nim saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
    nama = iNama; // Menetapkan nilai parameter iNama ke variabel anggota nama. Dengan menggunakan this->nama, kita dapat mengakses variabel anggota nama dalam konteks kelas mahasiswa, sehingga kita dapat memberikan nilai awal untuk variabel anggota nama saat objek dibuat, sehingga kita dapat mengelola informasi tentang mahasiswa dengan lebih efektif.
}

void mahasiswa::cetak() // Fungsi cetak adalah sebuah fungsi anggota dalam kelas mahasiswa yang digunakan untuk menampilkan informasi tentang mahasiswa, termasuk NIM dan Nama. Fungsi ini akan mencetak nilai NIM dan Nama mahasiswa ke layar menggunakan cout. Dengan menggunakan fungsi cetak, kita dapat dengan mudah melihat informasi lengkap tentang setiap mahasiswa yang dibuat, termasuk NIM dan Nama yang telah diinisialisasi melalui konstruktor dengan parameter atau konstruktor default.
{
    cout << "NIM: " << nim << endl; // this->nim digunakan untuk mengakses variabel anggota nim dalam konteks kelas mahasiswa. Dalam fungsi cetak, kita mencetak nilai NIM mahasiswa ke layar menggunakan cout dengan format "NIM: " diikuti oleh nilai nim yang telah diinisialisasi melalui konstruktor dengan parameter atau konstruktor default. Dengan menggunakan this->nim, kita memastikan bahwa kita mengakses variabel anggota yang benar dalam konteks kelas mahasiswa, sehingga kita dapat menampilkan informasi tentang NIM mahasiswa dengan benar.
    cout << "Nama: " << nama << endl; // this->nama digunakan untuk mengakses variabel anggota nama dalam konteks kelas mahasiswa. Dalam fungsi cetak, kita mencetak nilai Nama mahasiswa ke layar menggunakan cout dengan format "Nama: " diikuti oleh nilai nama yang telah diinisialisasi melalui konstruktor dengan parameter atau konstruktor default. Dengan menggunakan this->nama, kita memastikan bahwa kita mengakses variabel anggota yang benar dalam konteks kelas mahasiswa, sehingga kita dapat menampilkan informasi tentang Nama mahasiswa dengan benar.
}

int main() // Fungsi main adalah fungsi utama dalam program C++ yang digunakan sebagai titik masuk untuk menjalankan program. Dalam fungsi main, kita membuat beberapa objek mahasiswa dengan menggunakan konstruktor yang berbeda, termasuk konstruktor default, konstruktor dengan satu parameter, dan konstruktor dengan dua parameter. Setelah membuat objek mahasiswa, kita memanggil fungsi cetak pada setiap objek untuk menampilkan informasi tentang mahasiswa tersebut, termasuk NIM dan Nama. Dengan menggunakan fungsi main, kita dapat menjalankan program dan melihat hasil output yang dihasilkan oleh objek mahasiswa yang dibuat dengan berbagai konstruktor, sehingga kita dapat memahami konsep constructor overloading dalam pemrograman berorientasi objek.
{
    mahasiswa mhs1; // Membuat objek mhs1 dari kelas mahasiswa dengan menggunakan konstruktor default. Saat objek mhs1 dibuat, konstruktor default mahasiswa akan dipanggil secara otomatis, dan pesan "Constructor Dengan Parameter Terpanggil" akan dicetak ke layar menggunakan cout, serta nilai NIM dan Nama yang telah diinisialisasi dengan nilai default akan ditampilkan. Dengan membuat objek mhs1 dengan konstruktor default, kita dapat melihat pesan tersebut setiap kali kita menjalankan program, sehingga kita dapat memahami konsep konstruktor default dalam pemrograman berorientasi objek.
    mahasiswa mhs2(12345); // Membuat objek mhs2 dari kelas mahasiswa dengan menggunakan konstruktor yang memiliki satu parameter untuk NIM. Saat objek mhs2 dibuat, konstruktor mahasiswa dengan satu parameter akan dipanggil secara otomatis dengan nilai parameter nim sebesar 12345. Konstruktor ini akan mencetak pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai NIM yang diberikan sebagai parameter, sementara Nama akan diinisialisasi dengan nilai default. Dengan membuat objek mhs2 dengan konstruktor yang memiliki satu parameter, kita dapat melihat pesan tersebut setiap kali kita menjalankan program, sehingga kita dapat memahami konsep konstruktor dengan satu parameter dalam pemrograman berorientasi objek.
    mahasiswa mhs3("Andi"); // Membuat objek mhs3 dari kelas mahasiswa dengan menggunakan konstruktor yang memiliki satu parameter untuk Nama. Saat objek mhs3 dibuat, konstruktor mahasiswa dengan satu parameter akan dipanggil secara otomatis dengan nilai parameter nama sebesar "Andi". Konstruktor ini akan mencetak pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai Nama yang diberikan sebagai parameter, sementara NIM akan diinisialisasi dengan nilai default. Dengan membuat objek mhs3 dengan konstruktor yang memiliki satu parameter, kita dapat melihat pesan tersebut setiap kali kita menjalankan program, sehingga kita dapat memahami konsep konstruktor dengan satu parameter dalam pemrograman berorientasi objek.
    mahasiswa mhs4(010203, "Santi"); // Membuat objek mhs4 dari kelas mahasiswa dengan menggunakan konstruktor yang memiliki dua parameter untuk NIM dan Nama. Saat objek mhs4 dibuat, konstruktor mahasiswa dengan dua parameter akan dipanggil secara otomatis dengan nilai parameter nim sebesar 010203 dan nama "Santi". Konstruktor ini akan mencetak pesan "Constructor Dengan Parameter Terpanggil" ke layar menggunakan cout, serta menampilkan nilai NIM dan Nama yang diberikan sebagai parameter. Dengan membuat objek mhs4 dengan konstruktor yang memiliki dua parameter, kita dapat melihat pesan tersebut setiap kali kita menjalankan program, sehingga kita dapat memahami konsep konstruktor dengan dua parameter dalam pemrograman berorientasi objek.

    cout << "Mahasiswa 1: " << endl; // Mencetak informasi tentang mahasiswa mhs1 ke layar menggunakan cout dengan format "Mahasiswa 1: " diikuti oleh pemanggilan fungsi cetak pada objek mhs1. Fungsi cetak akan menampilkan nilai NIM dan Nama mahasiswa mhs1 ke layar menggunakan cout. Dengan memanggil fungsi cetak pada objek mhs1, kita dapat melihat informasi lengkap tentang mahasiswa tersebut, termasuk NIM dan Nama yang telah diinisialisasi melalui konstruktor default.
    mhs1.cetak(); // Memanggil fungsi cetak pada objek mhs1 untuk mencetak informasi tentang mahasiswa mhs1, termasuk NIM dan Nama. Fungsi cetak akan menampilkan nilai NIM dan Nama mahasiswa mhs1 ke layar menggunakan cout. Dengan memanggil fungsi cetak pada objek mhs1, kita dapat melihat informasi lengkap tentang mahasiswa tersebut, termasuk NIM dan Nama yang telah diinisialisasi melalui konstruktor default.
    cout << "Mahasiswa 2: " << endl; // Mencetak informasi tentang mahasiswa mhs2 ke layar menggunakan cout dengan format "Mahasiswa 2: " diikuti oleh pemanggilan fungsi cetak pada objek mhs2. Fungsi cetak akan menampilkan nilai NIM dan Nama mahasiswa mhs2 ke layar menggunakan cout. Dengan memanggil fungsi cetak pada objek mhs2, kita dapat melihat informasi lengkap tentang mahasiswa tersebut, termasuk NIM yang telah diinisialisasi melalui konstruktor dengan satu parameter, serta Nama yang telah diinisialisasi dengan nilai default.
    mhs2.cetak();
    cout << "Mahasiswa 3: " << endl;
    mhs3.cetak();
    cout << "Mahasiswa 4: " << endl;
    mhs4.cetak();

    return 0;
}