#include <iostream>
using namespace std;

class angka // Kelas angka adalah sebuah kelas yang digunakan untuk merepresentasikan sebuah kumpulan angka. Kelas ini memiliki variabel anggota arr yang merupakan pointer ke array dinamis untuk menyimpan angka-angka, serta variabel anggota panjang yang digunakan untuk menyimpan jumlah elemen dalam array. Kelas ini juga memiliki konstruktor yang digunakan untuk menginisialisasi array dengan panjang tertentu, serta destruktor yang digunakan untuk membebaskan memori yang dialokasikan untuk array ketika objek dari kelas angka dihancurkan. Selain itu, kelas ini memiliki fungsi cetakData untuk mencetak isi array ke layar, dan fungsi isiData untuk mengisi nilai-nilai dalam array melalui input dari pengguna.
{
private: // Variabel anggota dan fungsi anggota dalam kelas angka dideklarasikan sebagai private, yang berarti mereka hanya dapat diakses dari dalam kelas itu sendiri. Dengan menggunakan private, kita dapat melindungi data dan fungsi dalam kelas angka dari akses langsung dari luar kelas, sehingga kita dapat mengontrol bagaimana data dan fungsi tersebut digunakan dan dimodifikasi. Dalam kelas angka, variabel anggota arr dan panjang serta fungsi cetakData dan isiData dideklarasikan sebagai private, sehingga mereka hanya dapat diakses dan digunakan oleh fungsi-fungsi dalam kelas angka, seperti konstruktor dan destruktor.
    int *arr; // Variabel anggota arr dalam kelas angka adalah sebuah pointer ke array dinamis yang digunakan untuk menyimpan angka-angka. Variabel ini akan dialokasikan memori secara dinamis dalam konstruktor berdasarkan panjang yang diberikan, dan akan dibebaskan memori tersebut dalam destruktor ketika objek dari kelas angka dihancurkan. Dengan menggunakan pointer ke array dinamis, kita dapat mengelola jumlah elemen dalam array secara fleksibel sesuai dengan kebutuhan, sehingga kita dapat menyimpan dan mengelola kumpulan angka dengan lebih efektif.
    int panjang;

public: // Fungsi anggota dalam kelas angka dideklarasikan sebagai public, yang berarti mereka dapat diakses dari luar kelas. Dengan menggunakan public, kita dapat membuat objek dari kelas angka dan mengakses fungsi-fungsi tersebut untuk mengelola data dalam objek tersebut, seperti mencetak isi array atau mengisi nilai-nilai dalam array melalui input dari pengguna. Dalam kelas angka, konstruktor, destruktor, fungsi cetakData, dan fungsi isiData dideklarasikan sebagai public, sehingga kita dapat menggunakan fungsi-fungsi tersebut untuk mengelola data dalam objek angka yang kita buat.
    angka(int); // Konstruktor adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian. Konstruktor ini akan dipanggil secara otomatis setiap kali objek dari kelas tersebut dibuat, dan biasanya digunakan untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas angka, konstruktor ini menerima parameter berupa panjang array yang akan digunakan untuk menginisialisasi array dinamis arr, serta mengisi nilai-nilai dalam array melalui fungsi isiData. Dengan menggunakan konstruktor, kita dapat memastikan bahwa setiap kali objek angka dibuat, array dinamis akan diinisialisasi dengan benar dan nilai-nilai dalam array akan diisi sesuai dengan panjang yang diberikan.
    ~angka(); // Destruktor adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan diawali dengan tanda tilde (~). Destruktor ini akan dipanggil secara otomatis ketika objek dari kelas tersebut dihancurkan, baik secara eksplisit menggunakan delete atau secara implisit ketika objek keluar dari scope. Dalam kelas angka, destruktor ini digunakan untuk membebaskan memori yang dialokasikan untuk array dinamis arr ketika objek dari kelas angka dihancurkan, sehingga kita dapat mencegah kebocoran memori dan memastikan bahwa sumber daya yang digunakan oleh objek tersebut dibersihkan dengan benar.
    void cetakData(); // Fungsi cetakData adalah sebuah fungsi anggota dalam kelas angka yang digunakan untuk mencetak isi array ke layar. Fungsi ini akan mengiterasi melalui elemen-elemen dalam array arr dan mencetak setiap elemen ke layar menggunakan cout. Dengan menggunakan fungsi cetakData, kita dapat dengan mudah melihat isi array yang telah diisi dengan nilai-nilai melalui fungsi isiData, sehingga kita dapat memverifikasi bahwa data dalam array telah diisi dengan benar.
    void isiData(); // Fungsi isiData adalah sebuah fungsi anggota dalam kelas angka yang digunakan untuk mengisi nilai-nilai dalam array melalui input dari pengguna. Fungsi ini akan mengiterasi melalui elemen-elemen dalam array arr dan meminta pengguna untuk memasukkan nilai untuk setiap elemen menggunakan cin. Dengan menggunakan fungsi isiData, kita dapat dengan mudah mengisi data dalam array sesuai dengan panjang yang telah ditentukan saat objek angka dibuat, sehingga kita dapat mengelola kumpulan angka dengan lebih efektif.
};

angka::angka(int i) // Konstruktor adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan tidak memiliki tipe pengembalian. Konstruktor ini akan dipanggil secara otomatis setiap kali objek dari kelas tersebut dibuat, dan biasanya digunakan untuk menginisialisasi variabel anggota atau melakukan tindakan tertentu saat objek dibuat. Dalam kelas angka, konstruktor ini menerima parameter berupa panjang array yang akan digunakan untuk menginisialisasi array dinamis arr, serta mengisi nilai-nilai dalam array melalui fungsi isiData. Dengan menggunakan konstruktor, kita dapat memastikan bahwa setiap kali objek angka dibuat, array dinamis akan diinisialisasi dengan benar dan nilai-nilai dalam array akan diisi sesuai dengan panjang yang diberikan.
{
    panjang = i; // Menetapkan nilai parameter i ke variabel anggota panjang. Dengan menggunakan this->panjang, kita dapat mengakses variabel anggota panjang dalam konteks kelas angka, sehingga kita dapat menginisialisasi panjang array yang akan digunakan untuk mengelola kumpulan angka dengan lebih efektif.
    arr = new int[i]; // Mengalokasikan memori secara dinamis untuk array arr dengan panjang i. Dengan menggunakan new int[i], kita dapat membuat array dinamis yang dapat menampung jumlah elemen sesuai dengan panjang yang diberikan, sehingga kita dapat mengelola kumpulan angka dengan lebih efektif.
    isiData(); // Memanggil fungsi isiData untuk mengisi nilai-nilai dalam array arr melalui input dari pengguna. Dengan memanggil fungsi isiData dalam konstruktor, kita dapat memastikan bahwa setiap kali objek angka dibuat, array dinamis akan diisi dengan nilai-nilai yang dimasukkan oleh pengguna, sehingga kita dapat mengelola kumpulan angka dengan lebih efektif.
}

angka::~angka() // Destruktor adalah sebuah fungsi khusus dalam kelas yang memiliki nama yang sama dengan nama kelas dan diawali dengan tanda tilde (~). Destruktor ini akan dipanggil secara otomatis ketika objek dari kelas tersebut dihancurkan, baik secara eksplisit menggunakan delete atau secara implisit ketika objek keluar dari scope. Dalam kelas angka, destruktor ini digunakan untuk membebaskan memori yang dialokasikan untuk array dinamis arr ketika objek dari kelas angka dihancurkan, sehingga kita dapat mencegah kebocoran memori dan memastikan bahwa sumber daya yang digunakan oleh objek tersebut dibersihkan dengan benar.
{
    cout << endl; // Mencetak baris kosong ke layar menggunakan cout untuk memberikan pemisah visual sebelum mencetak pesan bahwa destruktor dipanggil dan memori telah dibebaskan. Dengan mencetak baris kosong, kita dapat membuat output yang lebih rapi dan mudah dibaca, sehingga kita dapat dengan jelas melihat pesan yang menunjukkan bahwa destruktor telah dipanggil dan memori telah dibebaskan.
    cetakData(); // Memanggil fungsi cetakData untuk mencetak isi array ke layar sebelum memanggil delete[] untuk membebaskan memori yang dialokasikan untuk array arr. Dengan memanggil fungsi cetakData sebelum membebaskan memori, kita dapat melihat isi array yang masih ada sebelum memori tersebut dibersihkan, sehingga kita dapat memahami bahwa data dalam array telah dihapus setelah destruktor dipanggil.
    delete[] arr; // Membebaskan memori yang dialokasikan untuk array arr menggunakan delete[]. Dengan menggunakan delete[], kita dapat memastikan bahwa memori yang dialokasikan untuk array dinamis arr dibebaskan dengan benar, sehingga kita dapat mencegah kebocoran memori dan memastikan bahwa sumber daya yang digunakan oleh objek angka dibersihkan dengan benar.
    cout << "Destructor dipanggil, memori telah dibebaskan." << endl; // Mencetak pesan "Destructor dipanggil, memori telah dibebaskan." ke layar menggunakan cout untuk memberi tahu bahwa destruktor telah dipanggil dan memori yang digunakan oleh objek angka telah dibebaskan. Dengan mencetak pesan ini, kita dapat dengan jelas melihat bahwa destruktor telah berfungsi dengan benar dalam membersihkan sumber daya yang digunakan oleh objek angka, sehingga kita dapat memahami konsep destruktor dalam pemrograman berorientasi objek.
}

void angka::isiData() // Fungsi isiData adalah sebuah fungsi anggota dalam kelas angka yang digunakan untuk mengisi nilai-nilai dalam array melalui input dari pengguna. Fungsi ini akan mengiterasi melalui elemen-elemen dalam array arr dan meminta pengguna untuk memasukkan nilai untuk setiap elemen menggunakan cin. Dengan menggunakan fungsi isiData, kita dapat dengan mudah mengisi data dalam array sesuai dengan panjang yang telah ditentukan saat objek angka dibuat, sehingga kita dapat mengelola kumpulan angka dengan lebih efektif.
{
    for (int i = 1; i <= panjang; i++) // Mengiterasi melalui elemen-elemen dalam array arr dari indeks 1 hingga panjang, dan meminta pengguna untuk memasukkan nilai untuk setiap elemen menggunakan
    {
        cout << i << " = "; // Mencetak prompt ke layar menggunakan cout untuk meminta pengguna memasukkan nilai untuk elemen ke-i dalam array arr. Dengan mencetak prompt ini, kita dapat memberikan petunjuk kepada pengguna tentang nilai yang harus dimasukkan untuk setiap elemen dalam array, sehingga kita dapat mengisi data dalam array dengan benar.
        cin >> arr[i]; // Membaca nilai yang dimasukkan oleh pengguna untuk elemen ke-i dalam array arr menggunakan cin, dan menyimpannya dalam array arr pada indeks i. Dengan menggunakan cin, kita dapat menerima input dari pengguna untuk mengisi data dalam array arr sesuai dengan panjang yang telah ditentukan saat objek angka dibuat, sehingga kita dapat mengelola kumpulan angka dengan lebih efektif.
    }
    cout << endl;
}

int main() // Fungsi main adalah fungsi utama dalam program C++ yang digunakan sebagai titik masuk untuk menjalankan program. Dalam fungsi main, kita membuat objek dari kelas angka dengan memberikan panjang array yang diinginkan, serta membuat pointer ke objek angka yang dialokasikan secara dinamis. Setelah itu, kita membebaskan memori yang dialokasikan untuk objek angka menggunakan delete, sehingga kita dapat melihat bagaimana destruktor dipanggil dan memori dibersihkan dengan benar. Dengan menggunakan fungsi main, kita dapat menjalankan program dan melihat hasil output yang dihasilkan oleh objek angka serta memahami konsep destruktor dalam pemrograman berorientasi objek.
{
    angka belajarcpp(3); // Membuat objek belajarcpp dari kelas angka dengan memberikan panjang array sebesar 3. Saat objek belajarcpp dibuat, konstruktor angka akan dipanggil secara otomatis dengan nilai parameter i sebesar 3, sehingga array dinamis arr akan diinisialisasi dengan panjang 3 dan nilai-nilai dalam array akan diisi melalui fungsi isiData. Dengan membuat objek belajarcpp dengan panjang array tertentu, kita dapat melihat bagaimana konstruktor bekerja untuk menginisialisasi data dalam objek tersebut, serta bagaimana destruktor bekerja untuk membersihkan sumber daya yang digunakan oleh objek tersebut ketika dihancurkan.
    angka *ptrBelajarcpp = new angka(5); // Membuat pointer ptrBelajarcpp yang menunjuk ke objek angka yang dialokasikan secara dinamis dengan memberikan panjang array sebesar 5. Saat objek yang dialokasikan secara dinamis dibuat, konstruktor angka akan dipanggil secara otomatis dengan nilai parameter i sebesar 5, sehingga array dinamis arr akan diinisialisasi dengan panjang 5 dan nilai-nilai dalam array akan diisi melalui fungsi isiData. Dengan membuat pointer ke objek angka yang dialokasikan secara dinamis, kita dapat melihat bagaimana kita dapat mengelola memori secara dinamis dalam program C++, serta bagaimana destruktor bekerja untuk membersihkan sumber daya yang digunakan oleh objek tersebut ketika dihancurkan menggunakan delete.
    delete ptrBelajarcpp; // Membebaskan memori yang dialokasikan untuk objek angka yang ditunjuk oleh ptrBelajarcpp menggunakan delete. Saat memori dibebaskan, destruktor angka akan dipanggil secara otomatis untuk membersihkan sumber daya yang digunakan oleh objek tersebut, sehingga kita dapat melihat pesan yang menunjukkan bahwa destruktor telah dipanggil dan memori telah dibebaskan. Dengan menggunakan delete untuk membebaskan memori yang dialokasikan secara dinamis, kita dapat memastikan bahwa sumber daya yang digunakan oleh objek angka dibersihkan dengan benar, sehingga kita dapat mencegah kebocoran memori dan memastikan bahwa program berjalan dengan efisien.

    return 0;
}